/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyLoansRouteImport } from './routes/_authenticated/my-loans'
import { Route as AuthenticatedMyFinesRouteImport } from './routes/_authenticated/my-fines'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedCatalogBookIdRouteImport } from './routes/_authenticated/catalog.$bookId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTaxonomyRouteImport } from './routes/_authenticated/admin/taxonomy'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminLoansRouteImport } from './routes/_authenticated/admin/loans'
import { Route as AuthenticatedAdminBooksRouteImport } from './routes/_authenticated/admin/books'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'
import { Route as AuthenticatedAdminBooksNewRouteImport } from './routes/_authenticated/admin/books.new'
import { Route as AuthenticatedAdminBooksBookIdEditRouteImport } from './routes/_authenticated/admin/books.$bookId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyLoansRoute = AuthenticatedMyLoansRouteImport.update({
  id: '/my-loans',
  path: '/my-loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyFinesRoute = AuthenticatedMyFinesRouteImport.update({
  id: '/my-fines',
  path: '/my-fines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogBookIdRoute =
  AuthenticatedCatalogBookIdRouteImport.update({
    id: '/$bookId',
    path: '/$bookId',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTaxonomyRoute =
  AuthenticatedAdminTaxonomyRouteImport.update({
    id: '/admin/taxonomy',
    path: '/admin/taxonomy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLoansRoute = AuthenticatedAdminLoansRouteImport.update({
  id: '/admin/loans',
  path: '/admin/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBooksRoute = AuthenticatedAdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBooksNewRoute =
  AuthenticatedAdminBooksNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminBooksRoute,
  } as any)
const AuthenticatedAdminBooksBookIdEditRoute =
  AuthenticatedAdminBooksBookIdEditRouteImport.update({
    id: '/$bookId/edit',
    path: '/$bookId/edit',
    getParentRoute: () => AuthenticatedAdminBooksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-fines': typeof AuthenticatedMyFinesRoute
  '/my-loans': typeof AuthenticatedMyLoansRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/books': typeof AuthenticatedAdminBooksRouteWithChildren
  '/admin/loans': typeof AuthenticatedAdminLoansRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/catalog/$bookId': typeof AuthenticatedCatalogBookIdRoute
  '/admin/books/new': typeof AuthenticatedAdminBooksNewRoute
  '/admin/books/$bookId/edit': typeof AuthenticatedAdminBooksBookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-fines': typeof AuthenticatedMyFinesRoute
  '/my-loans': typeof AuthenticatedMyLoansRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/books': typeof AuthenticatedAdminBooksRouteWithChildren
  '/admin/loans': typeof AuthenticatedAdminLoansRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/catalog/$bookId': typeof AuthenticatedCatalogBookIdRoute
  '/admin/books/new': typeof AuthenticatedAdminBooksNewRoute
  '/admin/books/$bookId/edit': typeof AuthenticatedAdminBooksBookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-fines': typeof AuthenticatedMyFinesRoute
  '/_authenticated/my-loans': typeof AuthenticatedMyLoansRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/books': typeof AuthenticatedAdminBooksRouteWithChildren
  '/_authenticated/admin/loans': typeof AuthenticatedAdminLoansRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/catalog/$bookId': typeof AuthenticatedCatalogBookIdRoute
  '/_authenticated/admin/books/new': typeof AuthenticatedAdminBooksNewRoute
  '/_authenticated/admin/books/$bookId/edit': typeof AuthenticatedAdminBooksBookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalog'
    | '/dashboard'
    | '/my-fines'
    | '/my-loans'
    | '/notifications'
    | '/profile'
    | '/auth/reset-password'
    | '/admin/audit-logs'
    | '/admin/books'
    | '/admin/loans'
    | '/admin/settings'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/catalog/$bookId'
    | '/admin/books/new'
    | '/admin/books/$bookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalog'
    | '/dashboard'
    | '/my-fines'
    | '/my-loans'
    | '/notifications'
    | '/profile'
    | '/auth/reset-password'
    | '/admin/audit-logs'
    | '/admin/books'
    | '/admin/loans'
    | '/admin/settings'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/catalog/$bookId'
    | '/admin/books/new'
    | '/admin/books/$bookId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/catalog'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-fines'
    | '/_authenticated/my-loans'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/auth/reset-password'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/books'
    | '/_authenticated/admin/loans'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/taxonomy'
    | '/_authenticated/admin/users'
    | '/_authenticated/catalog/$bookId'
    | '/_authenticated/admin/books/new'
    | '/_authenticated/admin/books/$bookId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-loans': {
      id: '/_authenticated/my-loans'
      path: '/my-loans'
      fullPath: '/my-loans'
      preLoaderRoute: typeof AuthenticatedMyLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-fines': {
      id: '/_authenticated/my-fines'
      path: '/my-fines'
      fullPath: '/my-fines'
      preLoaderRoute: typeof AuthenticatedMyFinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/$bookId': {
      id: '/_authenticated/catalog/$bookId'
      path: '/$bookId'
      fullPath: '/catalog/$bookId'
      preLoaderRoute: typeof AuthenticatedCatalogBookIdRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/taxonomy': {
      id: '/_authenticated/admin/taxonomy'
      path: '/admin/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AuthenticatedAdminTaxonomyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/loans': {
      id: '/_authenticated/admin/loans'
      path: '/admin/loans'
      fullPath: '/admin/loans'
      preLoaderRoute: typeof AuthenticatedAdminLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/books': {
      id: '/_authenticated/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AuthenticatedAdminBooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/books/new': {
      id: '/_authenticated/admin/books/new'
      path: '/new'
      fullPath: '/admin/books/new'
      preLoaderRoute: typeof AuthenticatedAdminBooksNewRouteImport
      parentRoute: typeof AuthenticatedAdminBooksRoute
    }
    '/_authenticated/admin/books/$bookId/edit': {
      id: '/_authenticated/admin/books/$bookId/edit'
      path: '/$bookId/edit'
      fullPath: '/admin/books/$bookId/edit'
      preLoaderRoute: typeof AuthenticatedAdminBooksBookIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminBooksRoute
    }
  }
}

interface AuthenticatedCatalogRouteChildren {
  AuthenticatedCatalogBookIdRoute: typeof AuthenticatedCatalogBookIdRoute
}

const AuthenticatedCatalogRouteChildren: AuthenticatedCatalogRouteChildren = {
  AuthenticatedCatalogBookIdRoute: AuthenticatedCatalogBookIdRoute,
}

const AuthenticatedCatalogRouteWithChildren =
  AuthenticatedCatalogRoute._addFileChildren(AuthenticatedCatalogRouteChildren)

interface AuthenticatedAdminBooksRouteChildren {
  AuthenticatedAdminBooksNewRoute: typeof AuthenticatedAdminBooksNewRoute
  AuthenticatedAdminBooksBookIdEditRoute: typeof AuthenticatedAdminBooksBookIdEditRoute
}

const AuthenticatedAdminBooksRouteChildren: AuthenticatedAdminBooksRouteChildren =
  {
    AuthenticatedAdminBooksNewRoute: AuthenticatedAdminBooksNewRoute,
    AuthenticatedAdminBooksBookIdEditRoute:
      AuthenticatedAdminBooksBookIdEditRoute,
  }

const AuthenticatedAdminBooksRouteWithChildren =
  AuthenticatedAdminBooksRoute._addFileChildren(
    AuthenticatedAdminBooksRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyFinesRoute: typeof AuthenticatedMyFinesRoute
  AuthenticatedMyLoansRoute: typeof AuthenticatedMyLoansRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminBooksRoute: typeof AuthenticatedAdminBooksRouteWithChildren
  AuthenticatedAdminLoansRoute: typeof AuthenticatedAdminLoansRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTaxonomyRoute: typeof AuthenticatedAdminTaxonomyRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyFinesRoute: AuthenticatedMyFinesRoute,
  AuthenticatedMyLoansRoute: AuthenticatedMyLoansRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminBooksRoute: AuthenticatedAdminBooksRouteWithChildren,
  AuthenticatedAdminLoansRoute: AuthenticatedAdminLoansRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTaxonomyRoute: AuthenticatedAdminTaxonomyRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
